version: "3.8"

services:
  postgres:
    image: postgres
    container_name: layer_postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movetask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo_db:
    image: mongo
    container_name: layer_mongo_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
